services:
    # Nginx Web Server
    nginx:
        image: nginx:latest
        container_name: gym-nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./gym-management:/var/www/html
        depends_on:
            - app
        networks:
            - gym-network

    # Laravel App (PHP-FPM)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: gym-app
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - gym-network

    # MySQL Database
    db:
        image: mysql:8
        container_name: gym-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gym_db
            MYSQL_USER: gym_user
            MYSQL_PASSWORD: gym_pass
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - gym-network

networks:
    gym-network:

volumes:
    db_data:
